name: Android Push Workflow

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - develop
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apk:
    name: Generate APK
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v2.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease
