name: Gradle Push Workflow

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2
      - name: Publish on Plugin Portal
        run: ./gradlew --project-dir projectinfoplugin setupPluginUploadFromEnvironment publishPlugins
        if: success()